// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pqalojdhgapnjnzulvas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxYWxvamRoZ2FwbmpuenVsdmFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxODc3NjAsImV4cCI6MjA2Mjc2Mzc2MH0.xkURKHV7VYPm0lGWDtP6szOEQLqH01iAtXfaDGP8ODU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);